import React, { useMemo } from 'react';
import { useApp } from '../App';
import { Card, Button } from '../components/UI';
import { format } from 'date-fns';
import { Flame, CheckCircle, AlertTriangle, TrendingUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Dashboard: React.FC = () => {
  const { user, data, dailyQuote } = useApp();
  const navigate = useNavigate();

  const greetings = useMemo(() => {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good Morning';
    if (hour < 18) return 'Good Afternoon';
    return 'Good Evening';
  }, []);

  const pendingTodos = data.todos.filter(t => !t.completed).length;
  const habits = data.tasks.filter(t => t.category === 'habit');
  const streak = 0; // Logic for calculating streak would process logs here

  return (
    <div className="space-y-8 animate-[fadeIn_0.5s_ease-out]">
      {/* Hero Section */}
      <div className="relative overflow-hidden rounded-3xl p-8 bg-gradient-to-r from-violet-600/40 to-indigo-600/40 border border-white/10 backdrop-blur-md">
        <div className="relative z-10">
          <h1 className="text-4xl font-bold text-white mb-2">
            {greetings}, {user?.username}
          </h1>
          <p className="text-indigo-200 text-lg">
            {format(new Date(), 'EEEE, MMMM do, yyyy')}
          </p>
          <div className="mt-6 p-4 bg-white/10 rounded-xl border border-white/10 max-w-2xl">
            <p className="italic text-gray-200">"{dailyQuote}"</p>
            <div className="text-xs text-indigo-300 mt-2 text-right">Generated by Gemini AI</div>
          </div>
        </div>
        {/* Abstract shapes background */}
        <div className="absolute -top-20 -right-20 w-64 h-64 bg-pink-500/30 rounded-full blur-3xl animate-float"></div>
        <div className="absolute -bottom-20 -left-20 w-64 h-64 bg-blue-500/30 rounded-full blur-3xl animate-float" style={{ animationDelay: '2s' }}></div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/tasks')}>
          <div className="p-4 bg-orange-500/20 rounded-full text-orange-400">
            <Flame size={32} />
          </div>
          <h3 className="text-xl font-bold">{streak} Day Streak</h3>
          <p className="text-sm text-gray-400">Keep the fire burning!</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/todos')}>
          <div className="p-4 bg-blue-500/20 rounded-full text-blue-400">
            <CheckCircle size={32} />
          </div>
          <h3 className="text-xl font-bold">{pendingTodos} Pending</h3>
          <p className="text-sm text-gray-400">Tasks on your To-Do list</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/expenses')}>
          <div className="p-4 bg-red-500/20 rounded-full text-red-400">
            <TrendingUp size={32} />
          </div>
          <h3 className="text-xl font-bold">High Expenses</h3>
          <p className="text-sm text-gray-400">Track your spending</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/calendar')}>
            <h3 className="text-xl font-bold text-gray-200">Calendar</h3>
            <p className="text-xs text-gray-400">View upcoming events</p>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <Card>
           <div className="flex justify-between items-center mb-4">
              <h3 className="font-bold text-lg">Active Habits</h3>
              <Button variant="ghost" onClick={() => navigate('/tasks')}>View All</Button>
           </div>
           <div className="space-y-4">
              {habits.slice(0, 3).map(h => (
                  <div key={h.id} className="p-3 bg-white/5 rounded-xl flex justify-between items-center">
                      <div>
                          <p className="font-medium">{h.name}</p>
                          <p className="text-xs text-gray-400">{h.reason}</p>
                      </div>
                      <span className="text-xs bg-indigo-500/20 text-indigo-200 px-2 py-1 rounded">{h.type}</span>
                  </div>
              ))}
              {habits.length === 0 && <p className="text-gray-500 text-center py-4">No active habits yet.</p>}
           </div>
        </Card>

        <Card>
            <div className="flex justify-between items-center mb-4">
              <h3 className="font-bold text-lg">Quick Actions</h3>
           </div>
           <div className="grid grid-cols-2 gap-4">
              <Button onClick={() => navigate('/journal')}>Write Journal</Button>
              <Button variant="ghost" onClick={() => navigate('/analytics')}>Check Analytics</Button>
              <Button variant="ghost" onClick={() => navigate('/profile')}>Update Profile</Button>
              <Button variant="danger" onClick={() => navigate('/settings')}>Settings</Button>
           </div>
        </Card>
      </div>
    </div>
  );
};

export default Dashboard;
