import React, { useMemo } from 'react';
import { useApp } from '../App';
import { Card, Button, Badge } from '../components/UI';
import { format, differenceInCalendarDays, parseISO } from 'date-fns';
import { Flame, CheckCircle, AlertTriangle, TrendingUp, Trophy, ZapOff } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Task, TaskLog } from '../types';

const Dashboard: React.FC = () => {
  const { user, data, dailyQuote } = useApp();
  const navigate = useNavigate();

  const greetings = useMemo(() => {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good Morning';
    if (hour < 18) return 'Good Afternoon';
    return 'Good Evening';
  }, []);

  const pendingTodos = data.todos.filter(t => !t.completed).length;
  // Include both Habits and Goals for streak tracking
  const trackedTasks = data.tasks.filter(t => t.category === 'habit' || t.category === 'goal');
  
  // --- Streak Logic ---
  const calculateStreak = (taskId: string, logs: TaskLog[]) => {
      const taskLogs = logs.filter(l => l.taskId === taskId && l.completed)
                           .sort((a, b) => b.date.localeCompare(a.date));
      if (taskLogs.length === 0) return { streak: 0, lastDate: null, brokenDate: null };

      const today = new Date();
      const yesterday = new Date(Date.now() - 86400000);
      const todayStr = format(today, 'yyyy-MM-dd');
      const yesterdayStr = format(yesterday, 'yyyy-MM-dd');

      const lastLogDateStr = taskLogs[0].date;
      
      // If last log is older than yesterday, streak is broken
      // Exception: If created recently and not daily, but let's assume daily habits for this logic
      if (lastLogDateStr !== todayStr && lastLogDateStr !== yesterdayStr) {
           const brokenDate = new Date(lastLogDateStr);
           brokenDate.setDate(brokenDate.getDate() + 1); // Broke the next day
           return { streak: 0, lastDate: lastLogDateStr, brokenDate: format(brokenDate, 'yyyy-MM-dd') };
      }

      let currentStreak = 1;
      let checkDate = new Date(lastLogDateStr);

      for (let i = 1; i < taskLogs.length; i++) {
          checkDate.setDate(checkDate.getDate() - 1); // Go back one day
          const checkDateStr = format(checkDate, 'yyyy-MM-dd');
          
          if (taskLogs[i].date === checkDateStr) {
              currentStreak++;
          } else {
              break; // Gap found
          }
      }
      return { streak: currentStreak, lastDate: lastLogDateStr, brokenDate: null };
  };

  const streakData = trackedTasks.map(h => ({ ...h, ...calculateStreak(h.id, data.logs) }));
  
  const brokenStreaks = streakData.filter(s => s.streak === 0 && s.brokenDate !== null)
                                  .sort((a, b) => (b.brokenDate || '').localeCompare(a.brokenDate || ''));
                                  
  const activeStreaks = streakData.filter(s => s.streak > 0).sort((a, b) => b.streak - a.streak);
  const totalStreak = activeStreaks.length > 0 ? Math.max(...activeStreaks.map(s => s.streak)) : 0; // Display max streak as "Main Streak"

  return (
    <div className="space-y-8 animate-[fadeIn_0.5s_ease-out]">
      {/* Hero Section */}
      <div className="relative overflow-hidden rounded-3xl p-8 bg-gradient-to-r from-violet-600/40 to-indigo-600/40 border border-white/10 backdrop-blur-md">
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
              <h1 className="text-4xl font-bold text-white mb-2">
                {greetings}, {user?.username}
              </h1>
              <p className="text-indigo-200 text-lg">
                {format(new Date(), 'EEEE, MMMM do, yyyy')}
              </p>
              <div className="mt-6 p-4 bg-white/10 rounded-xl border border-white/10 max-w-2xl">
                <p className="italic text-gray-200">"{dailyQuote}"</p>
                <div className="text-xs text-indigo-300 mt-2 text-right">Generated by Gemini AI</div>
              </div>
          </div>
          
          <div className="flex flex-col items-center bg-white/10 p-4 rounded-2xl border border-white/10 backdrop-blur-lg">
              <Trophy size={40} className="text-yellow-400 mb-2 animate-bounce" />
              <span className="text-3xl font-bold text-white">{user?.points || 0}</span>
              <span className="text-xs text-indigo-200 uppercase tracking-widest">Points</span>
          </div>
        </div>
        {/* Abstract shapes background */}
        <div className="absolute -top-20 -right-20 w-64 h-64 bg-pink-500/30 rounded-full blur-3xl animate-float"></div>
        <div className="absolute -bottom-20 -left-20 w-64 h-64 bg-blue-500/30 rounded-full blur-3xl animate-float" style={{ animationDelay: '2s' }}></div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/tasks')}>
          <div className="p-4 bg-orange-500/20 rounded-full text-orange-400">
            <Flame size={32} />
          </div>
          <h3 className="text-xl font-bold">{totalStreak} Day Streak</h3>
          <p className="text-sm text-gray-400">Best active streak</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/todos')}>
          <div className="p-4 bg-blue-500/20 rounded-full text-blue-400">
            <CheckCircle size={32} />
          </div>
          <h3 className="text-xl font-bold">{pendingTodos} Pending</h3>
          <p className="text-sm text-gray-400">Tasks on your To-Do list</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/expenses')}>
          <div className="p-4 bg-red-500/20 rounded-full text-red-400">
            <TrendingUp size={32} />
          </div>
          <h3 className="text-xl font-bold">High Expenses</h3>
          <p className="text-sm text-gray-400">Track your spending</p>
        </Card>

        <Card className="flex flex-col items-center justify-center text-center space-y-2 hover:bg-white/10 transition-colors cursor-pointer" onClick={() => navigate('/calendar')}>
            <h3 className="text-xl font-bold text-gray-200">Calendar</h3>
            <p className="text-xs text-gray-400">View upcoming events</p>
        </Card>
      </div>
      
      {/* Streaks Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
           {/* Active Streaks List */}
           <Card className="lg:col-span-2">
               <div className="flex justify-between items-center mb-4">
                  <h3 className="font-bold text-lg flex items-center gap-2"><Flame className="text-orange-400" size={20} /> Active Streaks</h3>
                  <Button variant="ghost" onClick={() => navigate('/tasks')}>View All</Button>
               </div>
               <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {activeStreaks.slice(0, 6).map(h => (
                      <div key={h.id} className="p-3 bg-white/5 rounded-xl flex justify-between items-center border border-white/5">
                          <div className="flex items-center gap-3">
                              <div className="w-8 h-8 rounded-full bg-orange-500/20 flex items-center justify-center text-orange-400 font-bold text-sm">
                                  {h.streak}
                              </div>
                              <div>
                                  <p className="font-medium">{h.name}</p>
                                  <Badge color={h.category === 'goal' ? 'bg-blue-500/20 text-blue-200' : 'bg-green-500/20 text-green-200'}>
                                      {h.category.toUpperCase()}
                                  </Badge>
                                  <p className="text-xs text-gray-400 mt-1">Last done: {h.lastDate}</p>
                              </div>
                          </div>
                          <div className="flex flex-col items-end">
                            <Badge color="bg-orange-500/10 text-orange-300">Active</Badge>
                          </div>
                      </div>
                  ))}
                  {activeStreaks.length === 0 && <p className="text-gray-500 text-center py-4 col-span-2">Start a habit or goal to see streaks!</p>}
               </div>
           </Card>

           {/* Broken Streaks */}
           <Card className="bg-red-900/10 border-red-500/20">
               <div className="flex justify-between items-center mb-4">
                  <h3 className="font-bold text-lg flex items-center gap-2 text-red-300"><ZapOff size={20} /> Recently Broken</h3>
               </div>
               <div className="space-y-3">
                  {brokenStreaks.slice(0, 5).map(h => (
                      <div key={h.id} className="p-3 bg-black/20 rounded-xl flex justify-between items-center">
                          <div>
                              <p className="font-medium text-gray-300">{h.name}</p>
                              <p className="text-xs text-red-400">Broke on: {h.brokenDate}</p>
                          </div>
                      </div>
                  ))}
                  {brokenStreaks.length === 0 && <p className="text-gray-500 text-center py-4">No broken streaks recently. Great job!</p>}
               </div>
           </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <Card>
            <div className="flex justify-between items-center mb-4">
              <h3 className="font-bold text-lg">Quick Actions</h3>
           </div>
           <div className="grid grid-cols-2 gap-4">
              <Button onClick={() => navigate('/journal')}>Write Journal</Button>
              <Button variant="ghost" onClick={() => navigate('/analytics')}>Check Analytics</Button>
              <Button variant="ghost" onClick={() => navigate('/profile')}>Update Profile</Button>
              <Button variant="danger" onClick={() => navigate('/settings')}>Settings</Button>
           </div>
        </Card>
      </div>
    </div>
  );
};

export default Dashboard;
