import React, { useState } from 'react';
import { useApp } from '../App';
import { backend } from '../services/mockBackend';
import { Card, Button, Input, Modal } from '../components/UI';
import { playSound } from '../constants';
import { useNavigate } from 'react-router-dom';

const Settings: React.FC = () => {
  const { user, data, logoutUser, refreshData } = useApp();
  const navigate = useNavigate();
  const [resetModalOpen, setResetModalOpen] = useState(false);
  const [secretAnswer, setSecretAnswer] = useState('');
  const [remark, setRemark] = useState('');

  const handleExport = () => {
      const jsonString = JSON.stringify(data, null, 2);
      const blob = new Blob([jsonString], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `glasshabit_backup_${user?.username}.json`;
      link.click();
      playSound('success');
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file || !user) return;
      const reader = new FileReader();
      reader.onload = async (event) => {
          try {
              const content = event.target?.result as string;
              // Check if valid JSON and matches structure roughly
              await backend.importData(user.id, content);
              await refreshData();
              alert('Data imported successfully!');
              playSound('success');
          } catch (err) {
              alert('Import Failed: Invalid file or format');
              playSound('error');
          }
      };
      reader.readAsText(file);
  };

  const handleReset = async () => {
      if (!user) return;
      try {
          await backend.resetData(user.id, secretAnswer);
          playSound('click');
          logoutUser();
          navigate('/login');
      } catch (err) {
          alert("Incorrect Secret Answer!");
          playSound('error');
      }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <h2 className="text-3xl font-bold">Settings</h2>

      <Card>
          <h3 className="font-bold mb-4 text-xl">Data Management</h3>
          <div className="space-y-4">
              <div>
                  <label className="block text-sm text-gray-400 mb-2">Export Data (JSON)</label>
                  <Button onClick={handleExport} variant="ghost" className="w-full">Download Backup</Button>
              </div>
              <div>
                  <label className="block text-sm text-gray-400 mb-2">Import Data</label>
                  <Input type="file" accept=".json" onChange={handleImport} />
                  <p className="text-xs text-gray-500 mt-2">Only import files generated by GlassHabit.</p>
              </div>
          </div>
      </Card>

      <Card className="border-red-500/30 bg-red-900/10">
          <h3 className="font-bold mb-4 text-xl text-red-400">Danger Zone</h3>
          <p className="text-sm text-gray-300 mb-4">Resetting your account will wipe all tasks, logs, and journals permanently.</p>
          <Button variant="danger" onClick={() => setResetModalOpen(true)} className="w-full">Reset All Data</Button>
      </Card>

      <div className="text-center">
          <Button variant="ghost" onClick={logoutUser}>Log Out</Button>
      </div>

      <Modal isOpen={resetModalOpen} onClose={() => setResetModalOpen(false)} title="Security Check">
          <div className="space-y-4">
              <p className="text-red-300">Enter your secret answer to confirm wipe.</p>
              <Input 
                 placeholder="Secret Answer (e.g. Pet Name)" 
                 value={secretAnswer} 
                 onChange={e => setSecretAnswer(e.target.value)} 
              />
               <Input 
                 placeholder="Type a remark why you are resetting" 
                 value={remark} 
                 onChange={e => setRemark(e.target.value)} 
                 required
              />
              <Button variant="danger" onClick={handleReset} className="w-full">Confirm Wipe & Logout</Button>
          </div>
      </Modal>
    </div>
  );
};

export default Settings;
